### ISSUE TITLE
Windows Terminal App

### ISSUE THREAD

**Issue by RomX2** [lighthaus-theme/lighthaus#1]
Hi, this is the code for the Windows Terminal app theme.

{"name": "Lighthaus",
"background": "#18191E",
"black": "#18181E",
"blue": "#1D918B",
"brightBlack": "#21252D",
"brightBlue": "#47A8A1",
"brightCyan": "#5AD1AA",
"brightGreen": "#50C16E",
"brightPurple": "#D68EB2",
"brightRed": "#FC5050",
"brightWhite": "#FFFADE",
"brightYellow": "#ED722E",
"cyan": "#00BFA4",
"foreground": "#EA549F",
"green": "#44B273",
"purple": "#D16BB7",
"red": "#FC2929",
"white": "#CCCCCC",
"yellow": "#E25600"}

**Comment by lighthaus-theme** [comment]
Hi @RomX2 
Thanks for writing.
The Windows Terminal theme is [here](https://github.com/lighthaus-theme/windows-terminal)
Try it out. 
If there are issues with it, do post them on the repo [here](https://github.com/lighthaus-theme/windows-terminal/issues).
