### ISSUE TITLE
VsCode

### ISSUE THREAD

**Issue by imran-vz** [lighthaus-theme/lighthaus#2]
Please make one for vs code. 😊

**Comment by lighthaus-theme** [comment]
> Please make one for vs code. 😊

Hey, thanks for reaching out.

VS Code theme is something I am working on, it's going slowly for now. Contributions and Forks are always welcome as well.
Cheers.

**Comment by imran-vz** [comment]
Yeah, I looked into it. Will be making a PR soon. I have a PR for Hyper. Please check it out. 😊

**Comment by lighthaus-theme** [comment]
> Yeah, I looked into it. Will be making a PR soon

Lemme know here before you submit a PR, I will make a. new repo there to see keep everything uniform.

> I have a PR for Hyper. Please check it out.

Replied to it on the PR thread.

**Comment by lighthaus-theme** [comment]
VS-Code theme just went live. https://github.com/lighthaus-theme/visual-studio-code
Can be installed from the [VS-Code Marketplace](https://marketplace.visualstudio.com/items?itemName=lighthaus-theme.lighthaus-vscode).

This issue can be closed successfully now.
