### ISSUE TITLE
Dark grey does not obey contrast ratio

### ISSUE THREAD

**Issue by henrebotha** [lighthaus-theme/lighthaus#3]
Per the readme:

> All colors have a min contrast ratio of 4.5 against the background color.

However, this is not true. Here is a screenshot of text being printed in dark grey, which is almost completely unreadable.

![image](https://user-images.githubusercontent.com/5593874/109645933-cf95bc00-7b57-11eb-8e68-d517bf548d82.png)

Lots of software (e.g. Vim) will use dark grey as a foreground colour (e.g. for comments), which makes this hard to use.

**Comment by lighthaus-theme** [comment]
Hey

Sorry it took this long for me to reply, been very busy with a few things lately and this message just slipped by me. 

> However, this is not true. Here is a screenshot of text being printed in dark grey, which is almost completely unreadable.

Thanks for pointing it out. This is a big error on my part and I will correct it asap. Lemme test out a few things and then start pushing updates.

Will post updates on this thread as well.

**Comment by henrebotha** [comment]
No stress! I know how open source works. Thanks for looking.

**Comment by lighthaus-theme** [comment]
Hey
I have changed the dark grey color.
New color is #8E8D8D

![HAL 9000 2021-03-30 21-54-59(1)](https://user-images.githubusercontent.com/68019163/113022965-cc1b4200-91a2-11eb-9833-5dff5af7750e.png)

I will be changing this in all of the repos, is gonna take a few days for all of them to be updated.
